Tutorial implementation
OwenVanRijn/vigilant-umbrella pull request #9
Opened 2022-04-01 09:56 UTC by rster2002

## Changes
The goal is to teach new players the game as it's not obvious what to do without first having played the game. This PR will focus on creating a scripted tutorial level where the player gets some guidance in the form of dialog popups.

## Tasks
- [ ] Go to next step in dialog interaction
- [ ] On dialog open/close
  - [ ] Disable player movement
  - [ ] Hide game UI (score/power etc)
  - [ ] Hide mobile controls
  - [ ] Pause gameplay loop (ghost spawning, solar panels)

## Notes
This is the first PR that uses Scriptable objects, so if there's any feedback on that, just leave a review on this PR.

2022-04-01 13:34 UTC, rster2002 commented
Also moved the textures into folders for better organisation.

2022-04-02 11:11 UTC, rster2002 commented
Prefabs and other assets that are accessed in the build should be placed in the resources folder. That's why `dialog.prefab` is moved to the `Resources/Prefabs` folder.

2022-04-02 11:14 UTC, rster2002 commented
@suchmememanyskill Can I split the GameUI script into the controller it is now and an Instance? It would make it a bit easier to hide it.

2022-04-02 11:15 UTC, suchmememanyskill commented
Fine by me

2022-04-05 12:46 UTC, suchmememanyskill requested changes

2022-04-05 12:46 UTC, suchmememanyskill commented on Demo/Demo/Assets/Scripts/Controllers/DialogController.cs
> +            return;
Why is this here? Start gets called before anything else gets called

2022-04-05 12:46 UTC, suchmememanyskill commented on Demo/Demo/Assets/Scripts/Controllers/HUDController.cs
> +            _hudObject ??= Instantiate(Resources.Load<GameObject>("Prefabs/GameHUD"), Vector3.zero,
You know you can create a GameObject field, and instantiate a prefab using that right?

2022-04-05 12:47 UTC, suchmememanyskill commented
Other than this i have no issues. Let me know if you need help merging demo-dev into tutorial

2022-04-05 12:51 UTC, rster2002 commented on Demo/Demo/Assets/Scripts/Controllers/HUDController.cs
> +            _hudObject ??= Instantiate(Resources.Load<GameObject>("Prefabs/GameHUD"), Vector3.zero,
This is intended to be more of a fail safe for if the object doesn't exist yet. Should this be removed?

2022-04-05 12:53 UTC, rster2002 commented on Demo/Demo/Assets/Scripts/Controllers/DialogController.cs
> +            return;
Sometimes the `PlayDialog` method gets called before the controller is initialised, so the `PlayDialog` method can also initialise the controller. This is here to prevent double initialisation. Don't really know how to prevent the method being called before the start method.

2022-04-05 17:46 UTC, suchmememanyskill commented on Demo/Demo/Assets/Scripts/Controllers/HUDController.cs
> +            _hudObject ??= Instantiate(Resources.Load<GameObject>("Prefabs/GameHUD"), Vector3.zero,
I'm not sure. I don't know how i feel about having a hardcoded text path. But assigning a gameobject (prefab) on everything you attach the script to doesn't sound ideal either

2022-04-05 17:49 UTC, rster2002 commented on Demo/Demo/Assets/Scripts/Controllers/HUDController.cs
> +            _hudObject ??= Instantiate(Resources.Load<GameObject>("Prefabs/GameHUD"), Vector3.zero,
I did this instead of adding a field to make it more 'plug-and-play' so in theory you only have to add this controller to a scene and it works.

Maybe the best middle-ground is to make `_hudObject` public and only create using the prefab when you don't assign one yourself?

2022-04-05 17:53 UTC, suchmememanyskill commented on Demo/Demo/Assets/Scripts/Controllers/HUDController.cs
> +            _hudObject ??= Instantiate(Resources.Load<GameObject>("Prefabs/GameHUD"), Vector3.zero,
That sounds better yeah. Thanks

2022-04-05 17:54 UTC, suchmememanyskill commented on Demo/Demo/Assets/Scripts/Controllers/HUDController.cs
> +            _hudObject ??= Instantiate(Resources.Load<GameObject>("Prefabs/GameHUD"), Vector3.zero,
Actually, would it be possible to let the gamemanager manage this? So you can request an instance off the gamemanager?

2022-04-06 10:25 UTC, suchmememanyskill approved these changes

2022-04-06 10:25 UTC, merged